### ISSUE TITLE
Cannot read property 'ensureAlive'

### ISSUE THREAD

**Issue by Imacreeper2013** [Vault74/Vault74#14]
Operating System: Windows 10 OS Version 1909 (18363.1198)
Browser version: Google Chrome 86.0.4240.198 (Official Build) (64-bit)
Vault74 version: Latest (https://ipfs.io/ipfs/QmcQB5WzgND3B2xC5pkzrCqE9grxZsPe2GvVVyuAMK7bR3/)
Bug: Uncaught TypeError: Cannot read property 'ensureAlive' of undefined

![Report Vault](https://user-images.githubusercontent.com/71351906/102704130-33cd0300-422c-11eb-8155-d47fe2e979d3.JPG)

**Comment by RetroPronghorn** [comment]
Let me know if this is resolved in the latest release, I'll leave this open for a day or two just in case.

**Comment by Imacreeper2013** [comment]
In the latest release I have not seen it occur so far
