### ISSUE TITLE
Muting the mic does not work #Tried on new version labeled as Mic muting should work

### ISSUE THREAD

**Issue by IamsickYT** [Vault74/Vault74#4]
Os version: Windows 10 OS Version 1709 (Build 16299.1087)
Browser version: 87.0.4280.66 (Official Build) (64-bit) (cohort: 87_66_Win)
Bug: mic muting doesent work 
How to reproduce:
try calling someone and try testing by muting your mic through the app and trying to speak to the other person
Extra Information:
Tested after the release of the latest link that stated that mic muting should work

**Comment by RetroPronghorn** [comment]
I am unable to reproduce this on my end, can you confirm you are on the correct version?

**Comment by Suryaansh2112** [comment]
The person who originally reported the bug in #bugs was MovingLand and his OS version etc is given above
I just checked if the muting function is working from this version of Vault 74
https://gateway.pinata.cloud/ipfs/QmNtuYLfXRMmso2raWFM7HPge5eaBAUK87BgbKDd29hqJA/
and it did not work here is the person who I tested with's and mine
The person who was able to hear it-
ToshiroHex
Browser-Firefox
OS Version- Windows 10 PRO
OS build-19041.630
The person who spoke(me)-
Google Chrome | 87.0.4280.66 (Official Build) (64-bit) (cohort: 87_66_Win)
OS | Windows 10 OS Version 1909 (Build 18363.1198)
JavaScript | V8 8.7.220.25
Flash | 32.0.0.453

**Comment by RetroPronghorn** [comment]
I was able to figure out the actual issue with this. The problem is if you start a call with your mic muted it does not apply, you need to unmute and remute. I will look into this in the future.

**Comment by Suryaansh2112** [comment]
I already checked if that was the issue I first spoke and then muted the mic it still lets my voice be heard and my mic does not mute itself

**Comment by RetroPronghorn** [comment]
This should now be resolved, other issues may still exist (1 known, the stream will not mute automatically if you make the call muted) but a new issue should be opened for this. Thus I'll open one.
