### ISSUE TITLE
Messaging Bugged

### ISSUE THREAD

**Issue by IamsickYT** [Vault74/Vault74#60]
I had called X user and was on the chat of the X user while another user Y messages me. The message from user Y ended up User X's chat and said Unable to decrypt. Although if you close and start the app again it fixes it but I am sure it is not intended how it is
![image](https://user-images.githubusercontent.com/64474891/106155417-abd10600-61a6-11eb-9b3b-f7c1a5310de4.png)

**Comment by RetroPronghorn** [comment]
Should be fixed.
