### ISSUE TITLE
Ice Cold theme status icon outline bug (Latest Release)

### ISSUE THREAD

**Issue by Imacreeper2013** [Vault74/Vault74#8]
Operating System: Windows 10 OS Version 1909 (18363.1198)
Browser version: Google Chrome 86.0.4240.198 (Official Build) (64-bit)
Vault74 version: Latest (QmQFg9aW8d9wv68izCb4BoePcarkmAwJp6uQ8z5CaAXktR/)
Bug: When using the Ice Cold theme the status icons are missing the black outline.
How to reproduce: Change theme to Ice Cold.

Solution: For the Ice Cold theme, change the -webkit-text-stroke-color:transparent; to -webkit-text-stroke-color:#1c1a24;

File Location: Line 2, Column 223985 of https://gateway.pinata.cloud/ipfs/QmQFg9aW8d9wv68izCb4BoePcarkmAwJp6uQ8z5CaAXktR/static/css/app.a97498da32957b5ab3bc.css?_sw-precache=e09fba76fa79469d6ab84589911fd505

**Comment by RetroPronghorn** [comment]
Themes will be reworked in the future, marking as wolntfix
